/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.vayneLove.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.vayneLove.service.StudentOperation;
import com.vayneLove.struts.form.StudentsForm;

/** 
 * MyEclipse Struts
 * Creation date: 06-30-2016
 * 
 * XDoclet definition:
 * @struts.action path="/findstua" name="studentsForm" scope="request"
 */
public class FindstuaAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		StudentsForm studentsForm = (StudentsForm) form;// TODO Auto-generated method stub
		
		StudentOperation op = new StudentOperation();
		
		if(op.findList(studentsForm.getStuid()))
		{
			return mapping.findForward("exist");
		}
		return mapping.findForward("noexist");
		
	}
}