/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.vayneLove.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.vayneLove.domain.Users;
import com.vayneLove.service.userValidateservice;
import com.vayneLove.struts.form.UserForm;

/** 
 * MyEclipse Struts
 * Creation date: 06-05-2016
 * 
 * XDoclet definition:
 * @struts.action path="/login" name="userForm" scope="request"
 */
public class LoginAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UserForm userForm = (UserForm) form;
		
		userValidateservice valiUser = new userValidateservice();
		Users user = new Users();
		user.setId((long)1);
		user.setName(userForm.getUsername());
		user.setPassword(userForm.getPassword());
		
		if (valiUser.checkLoginer(user)) {
			
			return mapping.findForward("ok");
		}
		
		return mapping.findForward("err");
	}
}