/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.vayneLove.struts.action;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.Action;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;

import com.vayneLove.domain.Users;
import com.vayneLove.service.RegisterUserService;
import com.vayneLove.struts.form.UserForm;

/** 
 * MyEclipse Struts
 * Creation date: 06-30-2016
 * 
 * XDoclet definition:
 * @struts.action path="/register" name="userForm" scope="request"
 */
public class RegisterAction extends Action {
	/*
	 * Generated Methods
	 */

	/** 
	 * Method execute
	 * @param mapping
	 * @param form
	 * @param request
	 * @param response
	 * @return ActionForward
	 */
	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UserForm userForm = (UserForm) form;// TODO Auto-generated method stub
		
		Users newuser = new Users();
		newuser.setName(userForm.getUsername());
		newuser.setPassword(userForm.getPassword());
		
		System.out.println(newuser.getName()+"  "+newuser.getPassword());
		
		RegisterUserService registerUserService = new RegisterUserService();
		registerUserService.register(newuser);
		
		return mapping.findForward("registerOk");
	}
}